### ISSUE TITLE
What about data it self contain Column  extractor

### ISSUE THREAD

**Issue by Dhvanit41** [darshit-shah/axiom-utils#32]
In **JSON2CSV** function if data it self contains Column extractor then it will give undesirable output.

**Comment by darshit-shah** [comment]
Can you provide sample json which will create this problem?

It will be solved ASAP and new version will be published.

Thanks,
Darshit.

**Comment by Dhvanit41** [comment]
```{
Description: ""Catherine Joker tag 1096955 HC2 9.95"
}```

**Comment by Dhvanit41** [comment]
`{
Description: ""Catherine Joker tag 1096955 HC2 9.95"
}`

**Comment by Dhvanit41** [comment]
{ Description: '"Something' }
